### ISSUE TITLE
Failed to load insomnia-plugin-universal-git

### ISSUE THREAD

**Issue by mjabalera** [riedeljan/insomnia-universal-git#1]
Ubuntu 20.04 clean installation
Stak trace:
```
Error: Cannot find module 'react'
Require stack:
- /home/miquel/.config/Insomnia/plugins/insomnia-plugin-universal-git/src/index.js
- /opt/Insomnia/resources/app.asar/renderer.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.i._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/miquel/.config/Insomnia/plugins/insomnia-plugin-universal-git/src/index.js:74:26)
    at Object.<anonymous> (/home/miquel/.config/Insomnia/plugins/insomnia-plugin-universal-git/src/index.js:319:3)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
```

**Comment by mjabalera** [comment]
**Version: Insomnia 2021.4.1
Release date: 7/7/2021
OS: Linux x64 5.4.0-77-generic
Electron: 9.3.5
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 zstd/1.4.9 libidn2/2.2.0 libssh2/1.9.0 nghttp2/1.41.0**

**Comment by riedeljan** [comment]
Hi! I'm aware of the issue. Seems like I didn't bundle react with the application and are working on bundling the plugin with webpack.

**Comment by riedeljan** [comment]
This issue is fixed with the latest releases.
